### ISSUE TITLE
Not working in Nuxt bridge

### ISSUE THREAD

**Issue by Draccano** [acidjazz/nuxt-tailvue#8]
The toast is not working after upgrade to the Nuxt bridge. Also the server shows several warnings (only when this plugin enabled).
```
 WARN  Compiled with 60 warnings                                                                                friendly-errors 23:20:44  


 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'BaseTransition' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'EMPTY_ARR' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'EMPTY_OBJ' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'Fragment' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'NO' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'NOOP' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'ReactiveEffect' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'Static' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'callWithAsyncErrorHandling' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'camelize' (imported as 'camelize$1') was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'camelize' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'capitalize' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'createHydrationRenderer' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'  
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'createRenderer' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'createVNode' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'def' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'extend' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'getGlobalThis' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'getTransitionRawChildren' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs' 
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'hasChanged' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'hasOwn' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'hyphenate' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'includeBooleanAttr' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'       
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/tailvue/node_modules/vue/dist/vue.runtime.esm-bundler.js  friendly-errors 23:20:44  

"export 'initCustomFormatter' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'      
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'invokeArrayFns' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isArray' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'isBuiltInDirective' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'isGloballyWhitelisted' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'    
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isHTMLTag' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js            friendly-errors 23:20:44  

"export 'isIntegerKey' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'isMap' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isModelListener' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isObject' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isOn' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'isPlainObject' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'isPromise' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'isReservedProp' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isRuntimeOnly' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isSVGTag' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isSet' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isSpecialBooleanAttr' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'     
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'isString' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js            friendly-errors 23:20:44  

"export 'isSymbol' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'looseEqual' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'looseIndexOf' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'makeMap' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'normalizeClass' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'normalizeStyle' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'pauseTracking' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'remove' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'resetTracking' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'resolveTransitionHooks' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'   
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'setTransitionHooks' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'       
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'toHandlerKey' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'toNumber' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'toRawType' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'track' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js        friendly-errors 23:20:44  

"export 'trigger' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                                                                                                                friendly-errors 23:20:44

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js          friendly-errors 23:20:44  

"export 'useTransitionState' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'       
                                                                                                                friendly-errors 23:20:44  

 WARN  in C:/Owlet/temp_github/turborepo/node_modules/tailvue/node_modules/vue/dist/vue.runtime.esm-bundler.js  friendly-errors 23:20:44  

"export 'warn' was not found in 'C:/Owlet/temp_github/turborepo/apps/frontend/.nuxt/runtime.vue2-bridge.4423da05.mjs'
                            
```

**Comment by acidjazz** [comment]
I would recommend trying https://github.com/fumeapp/tailvue

**Comment by Draccano** [comment]
@acidjazz Thank you for the suggestion. However, I use Nuxt 2 with enabled nuxt-bridge. The lib seems to work only in nuxt 3, because after installing that, there appeared error.
```js
reactivity.esm-bundler.js?6a74:516 Uncaught TypeError: Object(...) is not a function
    at eval (reactivity.esm-bundler.js?6a74:516:1)
    at ../../node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js (app.js:557:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (runtime-core.esm-bundler.js?0c97:1:1)
    at ../../node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js (app.js:569:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (runtime-dom.esm-bundler.js?9a05:1:1)
    at ../../node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js (app.js:581:1)
```
